name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Display Version
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.semVer }} --output .

      - name: Create Release and Upload Asset
        run: |
          gh release create v${{ env.GitVersion_MajorMinorPatch }} \
            --title "Release v${{ env.GitVersion_MajorMinorPatch }}" \
            --generate-notes

          gh release upload v${{ env.GitVersion_MajorMinorPatch }} \
            ./GossNet.Protocol.${{ steps.gitversion.outputs.semVer }}.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to GitHub Packages
        run: |
          # Remove the source if it exists, then add it
          dotnet nuget remove source github || true
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

          # Push package
          dotnet nuget push "*.nupkg" --source github --skip-duplicate